collections:
  authors:
    output: true
  posts:
    output: true

defaults:
  - scope:
      path: 
      type: "authors"
    values:
      layouts: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl: "/resume-page"

# paginate: 1
# paginate_path: "/authors/page:num/"

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

theme: minimal-mistakes-jekyll